# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-08 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tag',
            new_name='name',
        ),
    ]
